#!/usr/bin/ksh

source /etc/putbagrc 2>/dev/null
source ~/.putbagrc 2>/dev/null
source .putbagrc 2>/dev/null
while getopts a:t:s:u: opt
do
    case "$opt" in
      a)  alimit="$OPTARG";;
      t)  tlimit="$OPTARG";;
      s)  sshpath="$OPTARG";;
      u)  desturl="$OPTARG";;
      \?)		# unknown flag
      	  echo >&2 \
	  "usage: $0 [-a <ttl>] [-t <expiry>] [file ...]"
	  exit 1;;
    esac
done
shift `expr $OPTIND - 1`

# publish file
scp -r $1 $sshpath || exit 1
# handle access limitations
[[ -n "$alimit" ]] && {
    tmp=$(mktemp)
    echo "$alimit" >$tmp
    dstfname=".${1##*/}.alimit"
    scp "$tmp" "$sshpath/$dstfname"
    rm $tmp
}
# handle time limitations
[[ -n "$tlimit" ]] && {
    tmp=$(mktemp)
    date -d "$tlimit" +%s >$tmp
    dstfname=".${1##*/}.tlimit"
    scp "$tmp" "$sshpath/$dstfname"
    rm $tmp
}

# copy url into clipboard
printf "$desturl$1" | xclip -i
# echo result url
echo "$desturl$1"
