* putbag
a set of small scripts allowing to share files easily using a remote
server which handles ssh and http.

** alimit.sh
... monitors ncsa logfiles for requests to limited files which after
exceeding their TTL are deleted from the disk. This is useful for
sharing files for a limited amount of downloads.

To alimit a file create a .<filename>.alimit file containing the
number of allowed (and successful) downloads.

*** Limitations
Only handles 200 requests, continuation, redirects, etc are not
covered

** example
Create a file and set the limit to 3 downloads
#+BEGIN_SRC sh
sudo sh -c 'rm alimit.log; echo 'asdf' >/var/www/limited; echo 3 >/var/www/.limited.alimit'
#+END_SRC
Run alimit
#+BEGIN_SRC sh
sudo ./alimit.sh
#+END_SRC
Execute 4 times:
#+BEGIN_SRC sh
# curl localhost/limited; curl localhost/.limited.alimit
#+END_SRC
Check out the log
#+BEGIN_SRC sh
# cat alimit.log
#+END_SRC

** tlimit.sh
A small cronjob that weeds out expired files from the monitored directory structure.
** publish
A tool that publishes files and directories to a webserver via ssh,
supports alimit/tlimit for a clean putbag.

#+BEGIN_SRC
# publish -a 10 -t "two weeks" funnyimage.png
http://www.example.com/~user/putbag/funnyimage.png
#+END_SRC

The result url is not only displayed, but also automatically copied to
the clipboard.
* nginx
You might want to limit access to the .alimit files themselves. Do so using:
#+BEGIN_SRC
        location ~ \..*\.[at]limit$ {
                deny all;
        }
#+END_SRC
